baseurl = "/"
title = "Fun90"
canonifyurls = true
paginate = 6
languageCode = "zh-cn"
MetaDataFormat = "yaml"
theme = "Gemini"
googleAnalytics = "UA-110673269-2" # delete or comment to disable Google Analytics JS generation
disqusShortname = "" #delete or comment to disable Disqus comments
enableRobotsTXT = true
disableLiveReload = true

[params]
  Keywords = "Java, Web, Mac, 软件"
  Author = "Fun90"
  recentPostCount = 3
  intro = ["I am a Java Developer", "Work in Changsha"]

[[params.social]]
  title = "Email"
  url = "mailto:congzi@live.com"
[[params.social]]
  title = "Github"
  url = "https://github.com/fun90"
[[params.social]]
  title = "RSS"
  url = ""


[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -200
[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = -180
[[menu.main]]
  name = "About"
  url = "/about"
  weight = -160
